### ISSUE TITLE
Linux: Windows System Colors not known on Linux, Scrollbars do not reskin

### ISSUE THREAD

**Issue by arminposchmann** [definite-d/PSG_Reskinner#10]
Hi i run your fine reskinner on linux (pysimplegui tkinter version). Thank you for all that work.  
I had to exchange the occurrence of SystemButtonFace etc, with color names known to tk on Linux (gray30, etc). I currently do not know how to get the default theme colors on all Linux Window Managers
Suggested Fix : 
if platform.system() == 'Linux':
    block with self colors and default colors

I am running with this change now, but scrollbars keep their colors.  Any Hint? 
They can also not be reconfigured with psg update calls. Otherwise i would do so after reskin.

**Comment by definite-d** [comment]
Version 3 is out now, @arminposchmann . I've completely re-written how Reskinner's color assignment system, and now all default themes should work. Please check it out and see if it fixes this issue.
