### ISSUE TITLE
[Bug] Using "---" in menu definitions results in unintended behavior.

### ISSUE THREAD

**Issue by arminposchmann** [definite-d/PSG_Reskinner#11]
I'd like to inform you, that i found a weird behaviour when using your fine reskinner plugin. 
I am using python 3.10.12 , psg  4.61.0.206,  tkinter 8.6.12  on a linuxmint 21.3 system.
When i added lines with '---' to my menu definitions, reskin does no longer work for all the widgets that use these menus.
widgets with no such menudef lines work as before and do the reskin.
Just want to inform you about this, because it took me some time to find out.

Workaround is to create the lines in menu with some other character for example  unicode U+23E4 Straightness.
Does not look as nice as the dashes, but works. It seems all other characters work as well.

Thank you for your great work.

**Comment by definite-d** [comment]
Thank you for bringing this to my attention. I will investigate.

**Comment by definite-d** [comment]
So, it turns out the issue was with how Reskinner handles menu configuration. It's been fixed, and will be out soon in a new release, after which this issue will be closed.

Thank you once more @arminposchmann for your report and interest in the project.

**Comment by definite-d** [comment]
The release is out here on GitHub and on PyPi. Please upgrade to the latest version with the command:

```shell
python -m pip install --upgrade PSG-Reskinner
```
