### ISSUE TITLE
Importing "ttk_part_mapping_dict" results in an Error

### ISSUE THREAD

**Issue by PNxZEN** [definite-d/PSG_Reskinner#3]
Importing the `ttk_part_mapping_dict` from the `PySimpleGUI` module results in an Import Error. Seems like removing its import also does not change anything in the codes. I think it just lies there and needs to be removed to fix the Import Error as it does not do anything in the module and PySimpleGUI does not have anything similar to `ttk_part_mapping_dict` as per the recent update. And most importantly, Everything works fine as per my tests :>

**Please check if anything breaks on removing that object on your side too. Thanks !

_Traceback::_
```
File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\psg_reskinner\__init__.py", line 2, in <module>
    from .__main__ import reskin, animated_reskin, toggle_transparency, __version__
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\psg_reskinner\__main__.py", line 34, in <module>
    from PySimpleGUI.PySimpleGUI import Window, theme_text_color, theme_slider_color, theme_progress_bar_color, \
ImportError: cannot import name 'ttk_part_mapping_dict' from 'PySimpleGUI.PySimpleGUI' (C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\PySimpleGUI\PySimpleGUI.py)
```

**Comment by definite-d** [comment]
The `ttk_part_mapping_dict` is used for customizing ttk scrollbars. Removing it from the import will break Reskinner if used on any element that has them. At least, that's the behavior I get.

Do you mind sharing your PySimpleGUI version? I want to try replicating the error.

**Comment by definite-d** [comment]
Ah, I see. I was running version 4.60.3.85. Just updated (v4.60.3.96), and I can see the same error now.

**Comment by definite-d** [comment]
It seems you're running the version of PySimpleGUI from pip which . You should update your PySimpleGUI version to the latest on GitHub, which can be done from the Test Harness demo.

Simply run the PySimpleGUI module instead of importing it, then click the red button at the bottom of the window to update.

**Comment by definite-d** [comment]
In the meantime I'll try disabling the ttk scrollbar ability for lower versions that don't support it.
