### ISSUE TITLE
ImportError: cannot import 'TITLEBAR_TEXT_KEY'

### ISSUE THREAD

**Issue by vitalNohj** [definite-d/PSG_Reskinner#6]
Hate to open an issue here for something that seems trivial, but it may help others.

Using PySimpleGUI 4.60.4 
Using PSG_Reskinner 2.3.5

### Error:
`ImportError: cannot import name 'TITLEBAR_TEXT_KEY' from 'PySimpleGUI.PySimpleGUI'`

Getting this error when attempting to run the example and in my own code. 

TITLEBAR_TEXT_KEY was added as of 4.60.3.89
`Addition of TITLEBAR_TEXT_KEY to provide access to custom titlebar titles`

However according to PyLance it doesn't exist.  

![image](https://user-images.githubusercontent.com/15671154/215678262-eb38b8dc-eaa0-492f-a4dc-a4c4bf5ca60a.png)

So I visited `...\site-packages\PySimpleGUI\PySimpleGUI.py` and alas, it doesn't exist.

![image](https://user-images.githubusercontent.com/15671154/215677639-e0001693-4005-4538-ab6a-d7683f74148a.png)

### The fix:
I added this line back into PySimpleGUI.py
`TITLEBAR_TEXT_KEY = '__TITLEBAR TEXT__'`

![image](https://user-images.githubusercontent.com/15671154/215676974-9bdf9c8c-302a-4c22-b065-f897a7f5712d.png)

Did PySimpleGUI remove this? What went wrong? I hate modifying modules, but it'll have to do for now.

Now it's working without any issues that I know of!
![image](https://user-images.githubusercontent.com/15671154/215677318-33679711-6d70-4b0f-9e7c-e90fd4d3d2f8.png)

**Comment by definite-d** [comment]
Hi @vitalNohj!

You're totally correct; @PySimpleGUI _did_ abruptly remove that constant from the code. I had in fact noticed the issue myself a while ago after updating, and I'm still thinking of a possible fix for it.

Perhaps in the meantime I'll open an issue on PySimpleGUI's repo regarding its removal.

By the way, the `TITLEBAR_TEXT_KEY` value is used for reskinning the window title for custom title bars, hence it's really only useful for people who wish to use that feature, so I should probably move that import somewhere else 🤔...

**Comment by PySimpleGUI** [comment]
> You're totally correct; @PySimpleGUI did abruptly remove that constant from the code.

`TITLEBAR_TEXT_KEY` has not been released yet.  It's only available on the GitHub version.  It was added after the major 4.60.0 release.

It should be noted that on PyPI there are 4 of the 4.60 releases and each are emergency patch releases.  

https://www.pysimplegui.org/en/latest/#4601-pysimplegui-22-may-2022

The code will be released in PyPI later this year.  The numbering of releases is a bit confusing at the moment due to the emergency patch releases going out.

**Comment by definite-d** [comment]
Oh, thanks for clarifying @PySimpleGUI
