### ISSUE TITLE
Demo code throws error

### ISSUE THREAD

**Issue by Jayify** [definite-d/PSG_Reskinner#9]
Demo code on readme throws an error when tested

### Code line causing error
`new = rc(safethemes)` (line 31)

### Error
_NameError: name 'safethemes' is not defined_

### Suggested fix
Replacing identified line with `new = rc(theme_list())` fixes the issue and runs correctly.
[change: safethemes -> theme_list()]

Alternatively define _safethemes_ list in the demo code.

**Comment by definite-d** [comment]
Just fixed this, thank you. 

The issue was an oversight on my end; that demo code is lifted directly from the source code (it's the exact same code that runs when the module is run instead of imported), and `safethemes` is well defined there to avoid stirring up issue #7. I apologize.

**Comment by Jayify** [comment]
No worries, glad I could help.
